---
# Tasks file for mp-env role
- name: copy skeleton directory
  copy:
    src: skel/
    dest: /etc/skel/
    owner: root
    group: root

- name: copy root bash profile
  copy:
    src: bash-profile-root
    dest: /root/.bash_profile
    owner: root
    group: root
    mode: 0644

- name: copy root bashrc
  copy:
    src: bashrc-root
    dest: /root/.bashrc
    owner: root
    group: root
    mode: 0644
...
