---
# Full playbook
- hosts: all
  tasks:
    - include: includes/install_xorg.yml
      tags: ['install_xorg', 'all']
    - include: includes/install_tools.yml
      tags: ['install_tools', 'all']
    - include: includes/install_fonts.yml
      tags: ['install_fonts', 'all']
  roles:
    - { role: mp-env, tags: ['mp-env', 'all'] }
    - { role: users, tags: ['users', 'all'] }
    - { role: desktop-env, tags: ['desktop-evn', 'all'] }

- hosts: virtual
  roles:
    - { role: vboxguest, tags: ['vboxguest', 'virtual'] }
...
