---
# Full playbook
- hosts: all
  pre_tasks:
    - import_tasks: imports/network_setup.yml
      tags: ['network_setup', 'all']
    - import_tasks: imports/install_xorg.yml
      tags: ['install_xorg', 'all']
    - import_tasks: imports/install_tools.yml
      tags: ['install_tools', 'all']
    - import_tasks: imports/install_fonts.yml
      tags: ['install_fonts', 'all']
  roles:
    - { role: mp-env, tags: ['mp-env', 'all'] }
    - { role: users, tags: ['users', 'all'] }
    - { role: desktop-env, tags: ['desktop-env', 'all'] }

- hosts: virtual
  roles:
    - { role: vboxguest, tags: ['vboxguest', 'virtual'] }
...
