---
- name: install openbox
  pacman: 
    name: openbox
    state: present

- name: copy openbox autostart script
  copy:
    src: openbox/autostart
    dest: /etc/xdg/openbox/autostart
    owner: root
    group: root
    mode: 0755

- name: copy openbox configs
  copy:
    src: openbox/{{ item }}
    dest: /etc/xdg/openbox/{{ item }}
    owner: root
    group: root
    mode: 0644
  with_items:
    - rc.xml
    - menu.xml

- name: install openbox utilities
  pacman: 
    name: [ 'obconf', 'oblogout']
    state: present
